version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telecomdb
    ports:
      - "8889:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=telecomdb
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
